#! /bin/sh

set -e

case "$1" in
    configure)
        if [ -e /etc/kernel/pve-efiboot-uuids ]; then
            echo "$0: legacy ESP list /etc/kernel/pve-efiboot-uuids found moving to /etc/kernel/proxmox-boot-uuids" 1>&2
            mv /etc/kernel/pve-efiboot-uuids /etc/kernel/proxmox-boot-uuids
        fi
        if [ -e /etc/kernel/pve-efiboot-manual-kernels ] && [ ! -e /etc/kernel/proxmox-boot-manual-kernels ]; then
            echo "$0: legacy manual kernel list /etc/kernel/pve-efiboot-manual-kernels found moving to /etc/kernel/proxmox-boot-manual-kernels" 1>&2
            mv /etc/kernel/pve-efiboot-manual-kernels /etc/kernel/proxmox-boot-manual-kernels
        fi

        proxmox-boot-tool reinit || true
    ;;

    triggered)
        proxmox-boot-tool reinit || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
