#! /bin/sh

set -e

case "$1" in
    install|upgrade)
        if ! dpkg -S /usr/sbin/grub-install|grep -q 'diversion by proxmox-kernel-helper'; then
            dpkg-divert --package proxmox-kernel-helper --add --rename \
                --divert /usr/sbin/grub-install.real /usr/sbin/grub-install
        fi
    ;;
    *)
        echo "ignoring unknown preinst command '$1'"
    ;;
esac

#DEBHELPER#

exit 0
